---

- name: Add Cloudera Manager yum repository
  yum_repository:
    name: cloudera-manager
    description: Cloudera Manager
    baseurl: "{{ cloudera_repository_baseurl }}"
    gpgkey: "{{ cloudera_repository_gpgkey }}"
    gpgcheck: yes
    enabled: yes
  when: 
  - ansible_os_family|lower == "redhat"
  